/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.InspectorWorkArea;

import Business.Business;
import Business.Merchant.Merchant;
import Business.ProductCatalog.Product;
import Business.ProductCatalog.Product.Status;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shaoyifan
 */
public class InspectorJFrame extends javax.swing.JFrame {

    /**
     * Creates new form InspectorJFrame
     */
    
    Business business;
    UserAccount userAccount;
    DefaultTableModel tableModel;
    public InspectorJFrame() {
        initComponents();
    }
    
    public InspectorJFrame(Business business, UserAccount userAccount ) {
        initComponents();
        this.business = business;
        this.userAccount = userAccount;
        this.tableModel = (DefaultTableModel) jTable1.getModel();
        populate();
    }
    
    public void populate(){
              tableModel.setRowCount(0);
        for (Merchant m : this.business.getMerchantDirectory().getMerchantList()) {
            for(Product p : m.getProductCatalog().getProductList()){
                Object[] row = new Object[7];
                row[0] = m.getPersonId();
                row[1] = p.getProductId();
                row[2] = p.getProductName();
                row[3] = p.getCategory();
                row[4] = p.getProductPrice();
                row[5] = p.getDescription();
                row[6] = p.getStatus();
                tableModel.addRow(row);
            }
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rejectBtn = new javax.swing.JButton();
        approveBtn = new javax.swing.JButton();
        productImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Merchant", "Product", "Category", "Price", "Description", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 798, 254));

        rejectBtn.setText("Reject");
        rejectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectBtnActionPerformed(evt);
            }
        });
        getContentPane().add(rejectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, -1, -1));

        approveBtn.setText("Approve");
        approveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(approveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, -1, -1));
        getContentPane().add(productImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 310, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtnActionPerformed
        // TODO add your handling code here:
        
         int selectedRow = jTable1.getSelectedRow();
        
        if(selectedRow >=0){
            
            String mname =String.valueOf(jTable1.getValueAt(selectedRow, 0));
            String pid = String.valueOf(jTable1.getValueAt(selectedRow, 1));
            
            Merchant m = this.business.getMerchantDirectory().findMerchantByName(mname);
            
            Product p = m.getProductCatalog().findProductByid(pid);
            
            p.setStatus(Status.APPROVED);
            this.populate();
                
        }else{
        
            JOptionPane.showMessageDialog(null, "Please select a row!");
                    
        }
    }//GEN-LAST:event_approveBtnActionPerformed

    private void rejectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectBtnActionPerformed
        // TODO add your handling code here:
             int selectedRow = jTable1.getSelectedRow();
        
        if(selectedRow >=0){
            
            String mid =String.valueOf(jTable1.getValueAt(selectedRow, 0));
            String pid = String.valueOf(jTable1.getValueAt(selectedRow, 1));
            
            Merchant m = this.business.getMerchantDirectory().findById(mid);
            
            Product p = m.getProductCatalog().findProductByid(pid);
            
            p.setStatus(Status.REJECTED);
            
            this.populate();
                
        }else{
        
            JOptionPane.showMessageDialog(null, "Please select a row!");
                    
        }
    }//GEN-LAST:event_rejectBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InspectorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InspectorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InspectorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InspectorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InspectorJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel productImage;
    private javax.swing.JButton rejectBtn;
    // End of variables declaration//GEN-END:variables
}
