/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.InspectorWorkArea;

import Business.Business;
import Business.Merchant.Merchant;
import Business.ProductCatalog.Product;
import Business.ProductCatalog.Product.Status;
import Business.ProductSchedule.ProductOffer;
import Business.ProductSchedule.Schedule;
import Business.UserAccount.UserAccount;
import UI.MainWorkArea.MainJFrame;
import java.awt.Image;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shaoyifan
 */
public class InspectorJFrame extends javax.swing.JFrame {

    /**
     * Creates new form InspectorJFrame
     */
    Business business;
    UserAccount userAccount;
    DefaultTableModel tableModel;

    public InspectorJFrame() {
        initComponents();
    }

    public InspectorJFrame(Business business, UserAccount userAccount) {
        initComponents();
        this.business = business;
        this.userAccount = userAccount;
        this.tableModel = (DefaultTableModel) jTable1.getModel();
        populate();
    }

    public void populate() {
        tableModel.setRowCount(0);
        for (Merchant m : this.business.getMerchantDirectory().getMerchantList()) {
            for (Product p : m.getProductCatalog().getProductList()) {

                Object[] row = new Object[5];
                row[0] = m.getMerchantName();
                row[1] = p.getProductName();
                row[2] = p.getCategory();
                row[3] = p.getProductPrice();
                row[4] = p.getStatus();
                tableModel.addRow(row);
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rejectBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        productImage = new javax.swing.JLabel();
        approveBtn1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1500, 1300));
        setMinimumSize(new java.awt.Dimension(1500, 1300));
        setPreferredSize(new java.awt.Dimension(1500, 1300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Merchant", "Product", "Category", "Price", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 798, 254));

        rejectBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        rejectBtn.setText("Reject");
        rejectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectBtnActionPerformed(evt);
            }
        });
        getContentPane().add(rejectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 553, 80, 30));

        viewBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        viewBtn.setText("view");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 80, 30));
        getContentPane().add(productImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 310, 180));

        approveBtn1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        approveBtn1.setText("Approve");
        approveBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(approveBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 90, 30));

        jButton2.setText("LOG OUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/amy-shamblen-pJ_DCj9KswI-unsplash.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, -440, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:

        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow >= 0) {

            String mid = String.valueOf(jTable1.getValueAt(selectedRow, 0));
            String pid = String.valueOf(jTable1.getValueAt(selectedRow, 1));

            Merchant m = this.business.getMerchantDirectory().findMerchantByName(mid);

            Product p = m.getProductCatalog().findProductByName(pid);

            ImageIcon ii = new ImageIcon(p.getProductImage());
            // resize image to fit jlabel
            Image image = ii.getImage().getScaledInstance(productImage.getWidth(), productImage.getHeight(), Image.SCALE_SMOOTH);
            productImage.setIcon(new ImageIcon(image));

        } else {

            JOptionPane.showMessageDialog(null, "Please select a row!");

        }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void rejectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow >= 0) {

            String mid = String.valueOf(jTable1.getValueAt(selectedRow, 0));
            String pid = String.valueOf(jTable1.getValueAt(selectedRow, 1));

            Merchant m = this.business.getMerchantDirectory().findMerchantByName(mid);

            Product p = m.getProductCatalog().findProductByName(pid);

            p.setStatus(Status.REJECTED);

            this.populate();

        } else {

            JOptionPane.showMessageDialog(null, "Please select a row!");

        }
    }//GEN-LAST:event_rejectBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1MouseClicked

    private void approveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtn1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow >= 0) {

            String mid = String.valueOf(jTable1.getValueAt(selectedRow, 0));
            String pid = String.valueOf(jTable1.getValueAt(selectedRow, 1));

            Merchant m = this.business.getMerchantDirectory().findMerchantByName(mid);

            Product p = m.getProductCatalog().findProductByName(pid);

            p.setStatus(Status.APPROVED);

            this.populate();

        } else {

            JOptionPane.showMessageDialog(null, "Please select a row!");

        }
    }//GEN-LAST:event_approveBtn1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new MainJFrame(this.business, this.userAccount).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InspectorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InspectorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InspectorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InspectorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InspectorJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveBtn1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel productImage;
    private javax.swing.JButton rejectBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
