/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemWorkArea;

import Business.Business;
import Business.Merchant.Merchant;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tianshiyun
 */
public class CreateJPanel extends javax.swing.JPanel {
    Business business;
    UserAccount userAccount;
    DefaultTableModel userTableModel;
    
    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel() {
        initComponents();
    }
    
    public CreateJPanel(Business business, UserAccount userAccount) {
        initComponents();
        this.business = business;
        this.userAccount = userAccount;
//        this.userTableModel = (DefaultTableModel) userTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setLocation(new java.awt.Point(1200, 1300));
        setMaximumSize(new java.awt.Dimension(1200, 1300));
        setMinimumSize(new java.awt.Dimension(1200, 1300));
        setPreferredSize(new java.awt.Dimension(1200, 1300));
        setSize(new java.awt.Dimension(1200, 1300));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Enter Password");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 118, 110, 33));

        password.setBackground(new java.awt.Color(244, 217, 217));
        password.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 118, 202, 33));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("User Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 100, 33));

        userName.setBackground(new java.awt.Color(244, 217, 217));
        userName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 58, 202, 33));

        jComboBox1.setBackground(new java.awt.Color(244, 217, 217));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "System_Manager", "Customer", "Ad_Admin", "Delivery_Admin", "Validation_Admin", "Merchant", "Live_Admin", "Delivery_Company" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 178, 202, 30));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Select Role");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 178, 98, 33));

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SIGN UP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 318, 35));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kier-in-sight-Tuo1C7bvkv8-unsplash.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1870, -970, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

//    public void display(){
//        userTableModel.setRowCount(0);
//        
//        String name = userName.getText();
//        String pass = password.getText();
//        String role = (String)jComboBox1.getSelectedItem();
//        
//                Object[] row = new Object[3];
//                row[0] = name;
//                row[1] = pass;
//                row[2] = role;
//                userTableModel.addRow(row);
//                                         
//    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UserAccountDirectory ua = this.business.getUserAccountDirectory();

        String name = userName.getText();
        String pass = password.getText();
        String role = (String) jComboBox1.getSelectedItem();
        if (name.isEmpty() ||  pass.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Please fill all fields.");
        } else {
            if (ua.accountExists(userName.getText(), role)) {
                JOptionPane.showMessageDialog(null, "Sorry credentials are taken.");
            } else {
                UserAccount user = this.business.getUserAccountDirectory().createUserAccount(name, pass, role);

                JOptionPane.showMessageDialog(null, "User: "+name+"\n"+"ID: "+ user.getAccountId()+"\n"+ "Role: "+role);

            }
        }
//        display();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField password;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
