/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AdvertisementWorkArea;

import Business.Advertisement.Advertisement;
import Business.Advertisement.AdvertisementDirectory;
import Business.Business;
import Business.Delivery.DeliveryAgent;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tianzhichen
 */
public class AdManagementJPanel extends javax.swing.JPanel {

    Business business;
    UserAccount userAccount;
    DefaultTableModel adTableModel;

    /**
     * Creates new form AdManagementJPanel
     */
    public AdManagementJPanel() {
        initComponents();
    }

    public AdManagementJPanel(Business business, UserAccount userAccount) {
        initComponents();
        this.business = business;
        this.userAccount = userAccount;
        this.adTableModel = (DefaultTableModel) adTable.getModel();
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldPopularity = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        adTable = new javax.swing.JTable();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 130, -1));

        jLabel3.setText("Price");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        add(fieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 130, -1));

        jLabel4.setText("Popularity");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        add(fieldPopularity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 130, -1));

        createBtn.setText("CREATE");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        adTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Price", "Popularity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        adTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(adTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 40, 330, 320));

        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, 30));

        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        AdvertisementDirectory ad = this.business.getAdvertisementDirectory();

        String name = fieldName.getText();
        double price = Double.valueOf(fieldPrice.getText());
        int popularity = Integer.valueOf(fieldPopularity.getText());

        this.business.getAdvertisementDirectory().createAd(name, price, popularity);
        populate();
    }//GEN-LAST:event_createBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = adTable.getSelectedRow();
        if (selectedRow >= 0) {
        Advertisement ad = (Advertisement) adTable.getValueAt(selectedRow, 0);
            
            ad.setAdName(fieldName.getText());
            ad.setAdPrice(Double.valueOf(fieldPrice.getText()));
            ad.setPopularity(Integer.valueOf(fieldPopularity.getText()));
            this.business.getAdvertisementDirectory().updateAd(ad);
            JOptionPane.showMessageDialog(null, "Updated successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "Invalid row");
        }
        populate();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = adTable.getSelectedRow();
        if (selectedRow >= 0) {
            Advertisement ad = (Advertisement) adTable.getValueAt(selectedRow, 0);
      
            this.business.getAdvertisementDirectory().removeAd(ad.getAdName());
            JOptionPane.showMessageDialog(null, "Deleted successfully!");
            populate();
        } else {
            
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void adTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel adTableModel = (DefaultTableModel) adTable.getModel();
        // set data to text field when row is selected
        String name = adTable.getValueAt(adTable.getSelectedRow(), 0).toString();
        double price = Double.valueOf(adTable.getValueAt(adTable.getSelectedRow(), 1).toString());
        int popularity = Integer.valueOf(adTable.getValueAt(adTable.getSelectedRow(), 2).toString());
        // set the textfield
        fieldName.setText(name);
        fieldPrice.setText(String.valueOf(price));
        fieldPopularity.setText(String.valueOf(popularity));

    }//GEN-LAST:event_adTableMouseClicked

    public void populate() {
        adTableModel.setRowCount(0);
        for (Advertisement a : this.business.getAdvertisementDirectory().getAdList()) {
            Object[] row = new Object[3];
            row[0] = a;
            row[1] = a.getAdPrice();
            row[2] = a.getPopularity();
            adTableModel.addRow(row);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adTable;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPopularity;
    private javax.swing.JTextField fieldPrice;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
