/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CustomerWorkArea;

import Business.Business;
import Business.Customer.Customer;
import Business.UserAccount.UserAccount;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author tianshiyun
 */
public class EditJPanel extends javax.swing.JPanel {
    Business business;
    UserAccount userAccount;
    /**
     * Creates new form EditJPanel
     */
    public EditJPanel() {
        initComponents();
    }
    public EditJPanel(Business business,UserAccount userAccount) {
        initComponents();
        this.business = business;
        this.userAccount = userAccount;
        userName.setText(this.userAccount.getUsername());
        password.setText(this.userAccount.getPassword());
        for(Customer c: this.business.getCustomerDirectory().getCustomerDirectory()){
            if(c.getName().equals(userAccount.getUsername())){
                fieldEmail.setText(c.getEmail());
                fieldPhone.setText(c.getPhoneNumber()+"");
                }
        
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldPhone = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("InaiMathi", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Enter Password");
        add(jLabel1);
        jLabel1.setBounds(163, 217, 98, 33);

        password.setBackground(new java.awt.Color(204, 204, 204));
        password.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(password);
        password.setBounds(283, 217, 202, 33);

        jLabel2.setFont(new java.awt.Font("InaiMathi", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("User Name");
        add(jLabel2);
        jLabel2.setBounds(163, 167, 66, 33);

        userName.setEditable(false);
        userName.setBackground(new java.awt.Color(204, 204, 204));
        userName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });
        add(userName);
        userName.setBounds(283, 167, 202, 33);

        jLabel4.setText("Email");
        add(jLabel4);
        jLabel4.setBounds(163, 277, 32, 17);
        add(fieldEmail);
        fieldEmail.setBounds(283, 277, 200, 30);

        jLabel5.setText("Phone");
        add(jLabel5);
        jLabel5.setBounds(163, 337, 36, 17);
        add(fieldPhone);
        fieldPhone.setBounds(283, 337, 200, 30);

        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton);
        updateButton.setBounds(164, 406, 320, 39);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/annie-spratt-HB-Kf9WLy_0-unsplash.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3);
        jLabel3.setBounds(0, 0, 650, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
    String name = userName.getText();
    String passwo = password.getText();
    String email = fieldEmail.getText();
    Long phone = Long.valueOf(fieldPhone.getText());
    Pattern p = Pattern.compile("\\d{10}");
        Pattern emailP = Pattern.compile("^[A-Za-z0-9+_.-]+@(.+)$");
        Matcher m1 = p.matcher(fieldPhone.getText());
        Matcher m2 = emailP.matcher(fieldEmail.getText());
        boolean b = m1.matches();
        boolean b2 = m2.matches();
    if(name.isEmpty() || passwo.isEmpty() || !b || !b2 || fieldPhone.getText().length() !=10|| email.isEmpty() || phone.toString().isEmpty()){
        JOptionPane.showMessageDialog(null, "Please fill all field in correct form!");
    }else{
        for(Customer c: this.business.getCustomerDirectory().getCustomerDirectory()){
            if(c.getName().equals(userAccount.getUsername())){
        c.setEmail(email);
        c.setName(name);
        c.setPassword(passwo);
        c.setPhoneNumber(phone);
        this.userAccount.setPassword(passwo);
        }else{
                JOptionPane.showMessageDialog(null, "Name exists!");
        }
    }
    
// TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField password;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
