/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CustomerWorkArea;

import Business.Business;
import Business.Customer.Customer;
import Business.Customer.Order;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tianshiyun
 */
public class ViewOrderJPanel extends javax.swing.JPanel {

    Business business;
    UserAccount userAccount;
    DefaultTableModel orderTableModel;

    /**
     * Creates new form ViewOrderJPanel
     */
    public ViewOrderJPanel() {
        initComponents();
        display();
    }

    public ViewOrderJPanel(Business business, UserAccount userAccount) {
        initComponents();
        this.business = business;
        this.userAccount = userAccount;
        this.orderTableModel = (DefaultTableModel) orderTable.getModel();
        
        display();
    }

    public void display() {
        orderTableModel.setRowCount(0);
        for(Customer c : this.business.getCustomerDirectory().getCustomerDirectory()){
            if(c.getName().equals(this.userAccount.getUsername())){
                for (Order o : c.getOrderList()) {

            Object[] row = new Object[3];
            row[0] = o.getId();
            System.out.println(o.getId());
            row[1] = o.getPrice();
            System.out.println(o.getPrice());
            row[2] = o.getStatus();
            orderTableModel.addRow(row);

        }
            }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        confirmButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(184, 167, 133));
        setMaximumSize(new java.awt.Dimension(1200, 1300));
        setMinimumSize(new java.awt.Dimension(1200, 1300));
        setPreferredSize(new java.awt.Dimension(1200, 1300));
        setSize(new java.awt.Dimension(1200, 1300));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Order Number", "Total Price", "Status"
            }
        ));
        jScrollPane3.setViewportView(orderTable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 400, 410));

        confirmButton.setBackground(new java.awt.Color(255, 204, 204));
        confirmButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(51, 51, 51));
        confirmButton.setText("Received");
        confirmButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/annie-spratt-nWiS2rgtVts-unsplash.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-840, -840, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        
        int selectedRow = orderTable.getSelectedRow();
        if (selectedRow >= 0) {
            String orderN = (String) orderTable.getValueAt(selectedRow, 0);
            for(Customer c : this.business.getCustomerDirectory().getCustomerDirectory()){
                 if(c.getName().equals(this.userAccount.getUsername())){
                    for (Order o : c.getOrderList()) {
                        if(o.getId().equals(orderN)){
                         o.setStatus(Order.Status.RECEIVED);
////                         orderTableModel.removeRow(selectedRow);
//                         
//                        Object[] row = new Object[3];
//                        row[0] = o.getId();
//                        System.out.println(o.getId());
//                        row[1] = o.getPrice();
//                        System.out.println(o.getPrice());
//                        row[2] = o.getStatus();
//                        orderTableModel.addRow(row);
                        
                        }
                    }
                    
                }
            }
            this.display();

        } else {

            JOptionPane.showMessageDialog(null, "Please select a row!");

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable orderTable;
    // End of variables declaration//GEN-END:variables
}
