/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.MerchantWorkArea;

import Business.Advertisement.Advertisement;
import Business.Business;
import Business.Merchant.Merchant;
import Business.ProductSchedule.Schedule;
import Business.UserAccount.UserAccount;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tianzhichen
 */
public class AdManagementJPanel extends javax.swing.JPanel {

    Business business;
    UserAccount userAccount;
    DefaultTableModel adTableModel;
    DefaultTableModel scheTableModel;

    /**
     * Creates new form orderManagementJPanel
     */
    public AdManagementJPanel() {
        initComponents();
    }

    public AdManagementJPanel(Business business, UserAccount userAccount) {
        initComponents();
        this.business = business;
        this.userAccount = userAccount;

        this.adTableModel = (DefaultTableModel) adTable.getModel();
        this.scheTableModel = (DefaultTableModel) scheTable.getModel();

        populateAd();
        populateDp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        adTable = new javax.swing.JTable();
        scheBox = new javax.swing.JComboBox();
        assignScheBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        scheTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1200, 1300));
        setMinimumSize(new java.awt.Dimension(1200, 1300));
        setPreferredSize(new java.awt.Dimension(1200, 1300));
        setSize(new java.awt.Dimension(1200, 1300));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel3.setText("Advertisment Management");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        adTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Ad", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(adTable);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 310, 250));

        add(scheBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 190, 30));

        assignScheBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        assignScheBtn.setText("BUY AD");
        assignScheBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignScheBtnActionPerformed(evt);
            }
        });
        add(assignScheBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, 30));

        scheTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Schedule", "Date", "Ad", "Popularity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(scheTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 340, 260));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ad.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/amy-shamblen-pJ_DCj9KswI-unsplash.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -430, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignScheBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignScheBtnActionPerformed
        // TODO add your handling code here:
        Schedule sche = (Schedule) scheBox.getSelectedItem();

        int selectedRow = adTable.getSelectedRow();

        Advertisement ad = (Advertisement) adTable.getValueAt(selectedRow, 0);
        ad.setSchedule(sche);
        sche.setAdvertisement(ad);
        populateSche();
    }//GEN-LAST:event_assignScheBtnActionPerformed

    public void populateAd() {
        adTableModel.setRowCount(0);
        for (Advertisement ad : this.business.getAdvertisementDirectory().getAdList()) {
            Object[] row = new Object[2];

            row[0] = ad;
            row[1] = ad.getAdPrice();
            
            adTableModel.addRow(row);
        }
    }

    public void populateSche() {

        scheTableModel.setRowCount(0);
        Merchant m = this.business.getMerchantDirectory().findMerchantByName(this.userAccount.getUsername());
        for (Schedule s : m.getScheduleDirectory().getScheduleList()) {

            Object[] row = new Object[4];

            row[0] = s;
            row[1] = s.getDate();
            row[2] = s.getAdvertisement().getAdName();
            row[3] = s.getAdvertisement().getPopularity();

            scheTableModel.addRow(row);
        }

    }

    public void populateDp() {

        scheBox.removeAllItems();
        Merchant m = this.business.getMerchantDirectory().findMerchantByName(this.userAccount.getUsername());
        for (Schedule s : m.getScheduleDirectory().getScheduleList()) {
            scheBox.addItem(s);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adTable;
    private javax.swing.JButton assignScheBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox scheBox;
    private javax.swing.JTable scheTable;
    // End of variables declaration//GEN-END:variables
}
