/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.MerchantWorkArea;

import Business.Business;
import Business.Customer.Order;
import Business.Delivery.DeliveryAgent;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tianzhichen
 */
public class DeliveryManagementJPanel extends javax.swing.JPanel {

    Business business;
    UserAccount userAccount;
    DefaultTableModel deliveryTableModel;

    /**
     * Creates new form DeliveryManagementJPanel
     */
    public DeliveryManagementJPanel() {
        initComponents();
    }

    public DeliveryManagementJPanel(Business business, UserAccount userAccount) {
        initComponents();
        this.business = business;
        this.userAccount = userAccount;

        this.deliveryTableModel = (DefaultTableModel) deliveryTable.getModel();
        populateDp();
        populateDelivey();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        deliveryTable = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        assignBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deliveryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order", "Customer", "Delivery", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        deliveryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deliveryTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(deliveryTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 380, 290));

        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 170, 30));

        assignBtn.setText("ASSIGN");
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });
        add(assignBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 80, 30));

        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 80, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        // TODO add your handling code here:
        DeliveryAgent agent = (DeliveryAgent) jComboBox1.getSelectedItem();

        int selectedRow = deliveryTable.getSelectedRow();

        Order o = (Order) deliveryTable.getValueAt(selectedRow, 0);
        o.setAgent(agent);
        agent.addDeliveryOrder(o);
        o.setStatus(Order.Status.READY);
        populateDelivey();
    }//GEN-LAST:event_assignBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = deliveryTable.getSelectedRow();

        if (selectedRow >= 0) {
            Order o = (Order) deliveryTable.getValueAt(selectedRow, 0);
            DeliveryAgent agent = (DeliveryAgent) jComboBox1.getSelectedItem();
            o.setAgent(agent);
            o.setStatus(Order.Status.READY);
            JOptionPane.showMessageDialog(null, "Updated successfully！");
        } else {

        }
        populateDelivey();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deliveryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel deliveryTableModel = (DefaultTableModel) deliveryTable.getModel();

        // set data to text field when row is selected
        Order o = (Order) deliveryTableModel.getValueAt(deliveryTable.getSelectedRow(), 0);
        DeliveryAgent agent = (DeliveryAgent) deliveryTableModel.getValueAt(deliveryTable.getSelectedRow(), 2);

        //set the textfield
        DeliveryAgent d = (DeliveryAgent) jComboBox1.getSelectedItem();
        o.setAgent(d);
    }//GEN-LAST:event_deliveryTableMouseClicked

    public void populateDelivey() {
        deliveryTableModel.setRowCount(0);
        for (Order o : this.business.getAllOrders().getOrderList()) {

            Object[] row = new Object[3];

            row[0] = o;
            row[1] = o.getCustomer().getName();
            row[2] = o.getAgent().getName();
            row[3] = o.getStatus();

            deliveryTableModel.addRow(row);
        }
    }

    public void populateDp() {
        jComboBox1.removeAllItems();

        for (DeliveryAgent d : this.business.getDeliveryAgentDirectory().getAgents()) {
            jComboBox1.addItem(d.toString());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignBtn;
    private javax.swing.JTable deliveryTable;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
