/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.MerchantWorkArea;

import Business.Business;
import Business.UserAccount.UserAccount;
import UI.CustomerWorkArea.ShoppingJPanel;
import UI.MainWorkArea.MainJFrame;

/**
 *
 * @author tianzhichen
 */
public class MerchantJFrame extends javax.swing.JFrame {

    Business business;
    UserAccount userAccount;

    /**
     * Creates new form MerchantJFrame
     */
    public MerchantJFrame() {
        initComponents();
    }

      public MerchantJFrame(Business business, UserAccount userAccount) {
        initComponents();
        this.business = business;
        this.userAccount = userAccount;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftJPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dashboardBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        proManaBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        liveScheBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        adInfoBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftJPanel.setBackground(new java.awt.Color(153, 0, 255));
        leftJPanel.setMaximumSize(new java.awt.Dimension(2147, 2147));
        leftJPanel.setPreferredSize(new java.awt.Dimension(400, 600));
        leftJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit_property_24px.png"))); // NOI18N
        leftJPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 70, 40));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel11.setText("DASHBOARD");
        leftJPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, -1));

        dashboardBtn.setBackground(new java.awt.Color(255, 153, 153));
        dashboardBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 17)); // NOI18N
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        leftJPanel.add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 330, 41));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sort_window_24px.png"))); // NOI18N
        leftJPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel13.setText("LOG OUT");
        leftJPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, -1, -1));

        logoutBtn.setBackground(new java.awt.Color(255, 204, 204));
        logoutBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        leftJPanel.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 330, 41));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/categorize_24px.png"))); // NOI18N
        leftJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 30, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel7.setText("PRODUCT MANAGEMENT");
        leftJPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 20));

        proManaBtn.setBackground(new java.awt.Color(255, 153, 153));
        proManaBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        proManaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proManaBtnActionPerformed(evt);
            }
        });
        leftJPanel.add(proManaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 330, 41));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shopping_cart_24px.png"))); // NOI18N
        leftJPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel9.setText("LIVESTREAMING SCHEDULE");
        leftJPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        liveScheBtn.setBackground(new java.awt.Color(255, 153, 153));
        liveScheBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        liveScheBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liveScheBtnActionPerformed(evt);
            }
        });
        leftJPanel.add(liveScheBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 330, 41));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/account_24px.png"))); // NOI18N
        leftJPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        jLabel5.setText("ADVERTISEMENT INFORMATION");
        leftJPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 250, 20));

        adInfoBtn.setBackground(new java.awt.Color(255, 153, 153));
        adInfoBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        adInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adInfoBtnActionPerformed(evt);
            }
        });
        leftJPanel.add(adInfoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 330, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/annie-spratt-HB-Kf9WLy_0-unsplash.jpg"))); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(3500, 2700));
        leftJPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2640, -260, 3000, 2730));

        jSplitPane1.setLeftComponent(leftJPanel);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/amy-shamblen-NmwkK1iKPVc-unsplash.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 2575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 2178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 2470, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new DashboardJPanel(this.business, this.userAccount));
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainJFrame(this.business, this.userAccount).setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void proManaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proManaBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new ProductManagementJPanel(this.business, this.userAccount));
    }//GEN-LAST:event_proManaBtnActionPerformed

    private void liveScheBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liveScheBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new ScheduleJPanel(this.business, this.userAccount));
    }//GEN-LAST:event_liveScheBtnActionPerformed

    private void adInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adInfoBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new AdManagementJPanel(this.business, this.userAccount));
    }//GEN-LAST:event_adInfoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MerchantJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MerchantJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MerchantJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MerchantJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MerchantJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adInfoBtn;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel leftJPanel;
    private javax.swing.JButton liveScheBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton proManaBtn;
    // End of variables declaration//GEN-END:variables
}
