/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.DeliveryAgentWorkArea;

import Business.Business;
import Business.Merchant.Merchant;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import UI.MainWorkArea.MainJFrame;
import UI.MerchantWorkArea.ProductManagementJPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tianzhichen
 */
public class DeliveryJFrame extends javax.swing.JFrame {

    private Business business;
    private UserAccount userAccount;

    /**
     * Creates new form DeliveryJFrame
     */
    public DeliveryJFrame() {
        initComponents();
        this.setVisible(true);
    }

    public DeliveryJFrame(Business business, UserAccount userAccount) {
        initComponents();
        this.setVisible(true);
          this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);

        this.business = business;
        this.userAccount = userAccount;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        deliveryCompBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        shipBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1500, 1300));
        setMinimumSize(new java.awt.Dimension(1500, 1300));
        setPreferredSize(new java.awt.Dimension(1500, 1300));

        jPanel1.setMaximumSize(new java.awt.Dimension(300, 1300));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 1300));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 1300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutBtn.setText("LOGOUT");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 130, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/google_forms_24px.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Delivery Management");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 160, 20));

        deliveryCompBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryCompBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deliveryCompBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 230, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add_user_group_woman_man_24px.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Shippment Management");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 180, 20));

        shipBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shipBtnActionPerformed(evt);
            }
        });
        jPanel1.add(shipBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 230, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/annie-spratt-HB-Kf9WLy_0-unsplash.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -70, -1, -1));

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1200, 1300));
        jPanel2.setMinimumSize(new java.awt.Dimension(1200, 1300));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 1300));
        jPanel2.setSize(new java.awt.Dimension(1200, 1300));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pawel-czerwinski-hR545CzxZxk-unsplash.jpg"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-610, -380, 6100, 4090));

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainJFrame(this.business, this.userAccount).setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void deliveryCompBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryCompBtnActionPerformed
        // TODO add your handling code here:
         jSplitPane1.setRightComponent(new DeliveryCompanyJPanel(this.business, this.userAccount));
    }//GEN-LAST:event_deliveryCompBtnActionPerformed

    private void shipBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shipBtnActionPerformed
        // TODO add your handling code here:
         jSplitPane1.setRightComponent(new ShippmentManagementJPanel(this.business, this.userAccount));
    }//GEN-LAST:event_shipBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deliveryCompBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton shipBtn;
    // End of variables declaration//GEN-END:variables
}
